### ISSUE TITLE
[Question] What are the use-cases for this project and how does it compare to standard CAP eventing/messaging?

### ISSUE THREAD

**Issue by js1972** [cap-js-community/event-queue#55] opened 2023-11-17 03:42 UTC
This looks like a very interesting project but after having read the documentation I'm none the wiser as to what is really does or what use cases it solves? I would love to learn more about it and understand why/when to use it and how it compares or is better than events in CAP standard that work with event mesh for example?
I understand that event mesh cant be used in multi-tenant situations and that may be this projects main use case.  ;-)

Also are there any CAP projects that use this plugin we can see as a reference?

**Comment by soccermax** [comment] 2023-11-17 10:49
Hi @js1972,

Thank you for reaching out and expressing interest in our project. The documentation is currently a work in progress, and we will be extending and improving it over the coming weeks to address the exact questions you've asked. In the meantime, let me try to answer your questions:

### What it does and what it solves:
- The packages provided enable efficient and streamlined asynchronous processing of any load, with full CAP and managed transaction support.
  - For instance, if you have a business process that sends notifications of any kind (e.g., Email), you can use the event-queue to publish an event using the same transaction used for processing the business process data. Publishing an event involves writing a database entry, which ensures transactional consistency as the event is committed or rolled back alongside the primary transaction of the business process. The event-queue processes the event after the business transaction is committed. This approach keeps the business process lean, and prevents the user from having to wait on the UI for the asynchronous load to be processed.
- Managed transactions:
  - Every event processor is called with a managed transaction similar to CAP handlers. This means that you don't need to manage transactions yourself, freeing you up to focus on writing business code.
- Load management (a crucial consideration if the app attracts many users):
  - If the event-queue is used for processing asynchronously, the package can control the load and prevent CPU/Memory peaks. This feature enables the load to be processed based on the available resources in the app. Additionally, the event-queue distributes the load to all available app instances where the event-queue is initialized. This means that the app-instance which is publishing the event doesn't need to be the one processing the event. This distribution also allows you to process the event on a different app than the one that published the event (supporting a microservice architecture if needed).
- Periodic events (currently in beta):
  - You can define periodic events that should run every X seconds. The event-queue also performs load management here, distributing the load to all available app instances.

### What are the differences from CAP events?
- The SAP event mesh is more suitable for cross-application or cross-product communication. The event-queue, on the other hand, focuses more on asynchronous processing and load balancing within the same application or product. It also offers full CAP support and DB-transaction management.
- Unlike the SAP event mesh, which is CAP-agnostic by design, the event-queue is tailored specifically for a CAP-application.
- Event clustering is another feature (e.g., if you have multiple email events to the same user, you might want to cluster the events and send one bundled email).
- The event-queue has fewer dependencies: it only uses the primary database and, if available, a Redis instance.
- This project natively integrates with CAP and is fully multi-tenancy enabled.

### Are there any CAP projects that use this plugin we can see as a reference?
This project originated from an SAP Cloud Product used by many customers who needed transactionally safe processing as well as built-in load management. With this package, the SAP solution processes approximately ~1 million events in 7 days (and growing). The solution is not open source, but you might want to check out the example project in this repository.

If you have any more questions feel free to reach out.

**Comment by js1972** [comment] 2023-11-17 12:19
Excellent answer - Thankyou. I'm excited to try this out now.

**Closed** 2023-11-17 12:19 UTC
